---
redis_version: "{{ redis_version }}"
redis_install_dir: "{{ redis_install_dir }}"
redis_config_dir: "{{ redis_config_dir }}"
redis_data_dir: "{{ redis_data_dir }}"
redis_log_dir: "{{ redis_log_dir }}"
redis_user: "{{ redis_user }}"
redis_port: "{{ redis_port }}"
redis_bind: "{{ redis_bind }}"
redis_password: "{{ redis_password }}"
redis_maxmemory: "{{ redis_maxmemory }}"
redis_maxmemory_policy: "{{ redis_maxmemory_policy }}"
cluster_enabled: "{{ cluster_enabled }}"
cluster_node_timeout: "{{ cluster_node_timeout }}"