---
vminsert_binary_url: "https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/{{ victoriametrics_version }}/vminsert-{{ victoriametrics_version }}-linux-amd64.tar.gz"
vminsert_data_path: "{{ vm_data_dir }}/vminsert"
vminsert_log_path: "{{ vm_log_dir }}/vminsert"

# vminsert 集群配置
vminsert_storage_nodes:
  - "http://{{ vmstorage_1_ip }}:{{ vmstorage_vminsert_port }}"
  - "http://{{ vmstorage_2_ip }}:{{ vmstorage_vminsert_port }}"
  - "http://{{ vmstorage_3_ip }}:{{ vmstorage_vminsert_port }}"