---
- name: restart mongodb
  ansible.builtin.systemd:
    name: mongodb
    state: restarted
    daemon_reload: true
  become: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true