---
- name: 部署 PostgreSQL
  hosts: postgresql
  gather_facts: true
  become: true
  roles:
    - postgresql

- name: 部署 SonarQube
  hosts: sonarqube
  gather_facts: true
  become: true
  roles:
    - sonarqube