---
- name: restart vmauth
  ansible.builtin.systemd:
    name: vmauth
    state: restarted
    daemon_reload: true
  become: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true