---
# Vector 默认变量

vector_version: "0.52.0"
vector_port: 8686
vector_http_listen_addr: "0.0.0.0:8686"
vector_config_path: "/etc/vector"
vector_data_path: "/opt/vector/data"
vector_log_path: "/opt/vector/logs"
vector_victorialogs_url: "http://{{ victorialogs_1_ip }}:9428/insert/jsonline/streams"
vector_user: "vector"