---
# vmstorage 默认变量

vmstorage_binary_url: "https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/{{ victoriametrics_version }}/vmstorage-{{ victoriametrics_version }}-linux-amd64.tar.gz"
vmstorage_binary_path: "{{ vm_install_dir }}/vmstorage-{{ victoriametrics_version }}-linux-amd64"
vmstorage_data_path: "{{ vm_data_dir }}/vmstorage"
vmstorage_log_path: "{{ vm_log_dir }}/vmstorage"

# vmstorage 集群配置
vmstorage_nodes:
  - "http://172.22.0.10:8401"
  - "http://172.22.0.11:8401"
  - "http://172.22.0.12:8401"