---
# vmselect 特定配置

vmselect_service_name: "vmselect"
vmselect_binary: "vmselect-prod"
vmselect_data_dir: "{{ vm_data_dir }}/vmselect"
vmselect_log_file: "{{ vm_log_dir }}/vmselect.log"

# 查询配置
vmselect_cache_size: "1048576"
vmselect_max_concurrent_inserts: 1000
vmselect_max_concurrent_requests: 1000
vmselect_memory_allowed_percent: 60
vmselect_search_max_points_per_timeseries: 30000
vmselect_search_max_unique_timeseries: 300000