---
- name: restart vmalert
  ansible.builtin.systemd:
    name: vmalert
    state: restarted
    daemon_reload: true
  become: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true