---
# 部署 MySQL 主从复制 + Orchestrator
- name: 部署 MySQL 主从复制集群
  hosts: mysql_cluster
  gather_facts: true
  become: true

  roles:
    - mysql

- name: 部署 Orchestrator
  hosts: orchestrator
  gather_facts: true
  become: true

  roles:
    - orchestrator