---
- name: restart grafana
  ansible.builtin.systemd:
    name: grafana
    state: restarted
    daemon_reload: true
  become: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true