---
- name: restart vmselect
  ansible.builtin.systemd:
    name: vmselect
    state: restarted
    daemon_reload: true
  become: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true