---
kafka_version: "3.7.0"
zookeeper_version: "3.9.2"
kafka_install_dir: "/usr/local/kafka"
zookeeper_install_dir: "/usr/local/zookeeper"
kafka_data_dir: "/data/kafka"
zookeeper_data_dir: "/data/zookeeper"
kafka_user: "kafka"
zookeeper_user: "zookeeper"
kafka_port: 9092
zookeeper_port: 2181
service_state: "started"
service_enabled: true