---
# Nginx GeoIP默认变量

nginx_config_dir: "/etc/nginx"
nginx_log_dir: "/var/log/nginx"
nginx_log_format_name: "geoip"

# Nginx日志格式配置
nginx_log_format: '$remote_addr - $remote_user [$time_local] '
    '"$request" $status $body_bytes_sent '
    '"$http_referer" "$http_user_agent" '
    '$request_time $upstream_response_time'