---
- name: restart mysql-router
  ansible.builtin.systemd:
    name: mysql-router
    state: restarted
    daemon_reload: true
  become: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true