---
vmselect_binary_url: "https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/{{ victoriametrics_version }}/vmselect-{{ victoriametrics_version }}-linux-amd64.tar.gz"
vmselect_data_path: "{{ vm_data_dir }}/vmselect"
vmselect_log_path: "{{ vm_log_dir }}/vmselect"

# vmselect 集群配置
vmselect_storage_nodes:
  - "http://172.22.0.10:8401"
  - "http://172.22.0.11:8401"
  - "http://172.22.0.12:8401"