---
vmselect_binary_url: "https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/{{ victoriametrics_version }}/vmselect-{{ victoriametrics_version }}-linux-amd64.tar.gz"
vmselect_data_path: "{{ vm_data_dir }}/vmselect"
vmselect_log_path: "{{ vm_log_dir }}/vmselect"

# vmselect 集群配置
vmselect_storage_nodes:
  - "http://{{ vmstorage_1_ip }}:{{ vmstorage_vmselect_port }}"
  - "http://{{ vmstorage_2_ip }}:{{ vmstorage_vmselect_port }}"
  - "http://{{ vmstorage_3_ip }}:{{ vmstorage_vmselect_port }}"