---
# VictoriaLogs 默认变量

victorialogs_version: "v1.43.1"
victorialogs_port: 9428
victorialogs_http_listen_addr: "0.0.0.0:9428"
victorialogs_data_path: "{{ vm_data_dir }}/victorialogs"
victorialogs_log_path: "{{ vm_log_dir }}/victorialogs"
victorialogs_retention_period: "30d"
victorialogs_memory_allowed_bytes: "1GB"