---
# Logstash handlers

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: restart logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted
  become: true