---
- name: restart orchestrator
  ansible.builtin.systemd:
    name: orchestrator
    state: restarted
    daemon_reload: true
  become: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true