---
- name: restart vmagent
  ansible.builtin.systemd:
    name: vmagent
    state: restarted
    daemon_reload: true
  become: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true