---
# vminsert 特定配置

vminsert_service_name: "vminsert"
vminsert_binary: "vminsert-prod"
vminsert_data_dir: "{{ vm_data_dir }}/vminsert"
vminsert_log_file: "{{ vm_log_dir }}/vminsert.log"

# 写入配置
vminsert_max_concurrent_inserts: 1000
vminsert_max_insert_request_size: 33554432
vminsert_max_labels_per_timeseries: 30
vminsert_memory_allowed_percent: 60